namespace AgenticRag.Models;

/// <summary>Chat request from user.</summary>
public sealed record ChatRequest(string Question, string? UserId = null);

/// <summary>Chat response including metadata.</summary>
public sealed record ChatResponse(
    string Answer,
    bool FromCache,
    int PlanSteps,
    int ReflectionAttempts,
    double ConfidenceScore);

/// <summary>Single step in an execution plan.</summary>
public sealed record PlanStep(
    int StepNumber,
    string Description,
    string ToolToUse,
    string ToolInput);

/// <summary>Execution plan generated by the Planner agent.</summary>
public sealed record ExecutionPlan(List<PlanStep> Steps);

/// <summary>Reflection result from the Reasoning agent.</summary>
public sealed record ReflectionResult(
    bool IsComplete,
    double ConfidenceScore,
    string? GapAnalysis,
    string? SuggestedAction,
    string? FinalAnswer);
